- name: Crear un grupo de prometheus
  group: name="{{ groupId }}"
  become: true

- name: Creando un usuario prometheus
  user:
    name: "{{ userId }}"
    group: "{{ groupId }}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{ userId }} nologin User"
    createhome: "no"
    state: present

- name: Instalando prometheus
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz"  
    dest: "/tmp/"
    remote_src: yes

- name: Copiando el archivo de prometheus a bin
  copy:
    src: "/tmp/prometheus-{{ version }}.linux-amd64/prometheus"
    dest: "/usr/local/bin/prometheus"
    owner: "{{ userId }}"
    group: "{{ groupId }}"
    remote_src: yes
    mode: 0755

- name: Delete prometheus tmp folder
  file: 
    path: '/tmp/prometheus-{{ version }}.linux-amd64'
    state: absent

- name: Creando directorio
  file:
    path: "/data/prometheus"
    state: directory
    owner: "{{ userId }}"
    group: "{{ groupId }}"
    mode: 0755

- name: Creando directorio
  file: 
    path: "/etc/prometheus"
    state: directory
    owner: "{{ userId }}"
    group: "{{ groupId }}"
    mode: 0755

- name: config file
  template: 
    src: prometheus.conf.j2
    dest: /etc/prometheus/prometheus.conf

- name: Copiando systemd init file
  template:
    src: init.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify: systemd_reload

- name: Iniciando el servicio de prometheus
  service:
    name: prometheus
    state: started
    enabled: yes

- name: Verificando si prometheus es accesible
  uri:
    url: http://localhost:9090
    method: GET
    status_code: 200